project:
  type: website
  resources:
    - ai-app.png
    - hands.jpg
    - handout-styles.css
    - tiktok.mp4

website:
  title: "AI as a Health Resource in Marginalized Communities"

render:
  - index.qmd
  - teach-in.qmd
  - handout.qmd